"""HTML dashboard generation with Plotly charts."""

import json
import logging
import os
from typing import Any, Dict, List, Optional

log = logging.getLogger("agent")

DASHBOARD_DIR = "outputs/dashboard"


def _ensure_dir() -> None:
    os.makedirs(DASHBOARD_DIR, exist_ok=True)


def _build_html(
    stats: Dict[str, Any],
    chart_divs: List[str],
    chart_scripts: List[str],
) -> str:
    total_scraped = stats.get("total_scraped", 0)
    total_recommended = stats.get("total_recommended", 0)
    total_applied = stats.get("total_applied", 0)
    runtime = stats.get("runtime_seconds", 0)

    charts_html = "\n".join(chart_divs)
    scripts_html = "\n".join(chart_scripts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI Jobs Agent — Dashboard</title>
<script src="https://cdn.plot.ly/plotly-2.34.0.min.js"></script>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; background:#f5f6fa; color:#2d3436; padding:20px; }}
.header {{ text-align:center; padding:30px 0; }}
.header h1 {{ font-size:28px; color:#0984e3; margin-bottom:8px; }}
.header p {{ color:#636e72; font-size:14px; }}
.stats-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(160px,1fr)); gap:16px; max-width:900px; margin:20px auto; }}
.stat-card {{ background:white; border-radius:12px; padding:20px; text-align:center; box-shadow:0 2px 8px rgba(0,0,0,0.06); }}
.stat-card .number {{ font-size:32px; font-weight:700; color:#0984e3; }}
.stat-card .label {{ font-size:13px; color:#636e72; margin-top:4px; }}
.charts {{ max-width:1200px; margin:0 auto; }}
.chart-container {{ background:white; border-radius:12px; padding:16px; margin:16px 0; box-shadow:0 2px 8px rgba(0,0,0,0.06); }}
.chart-container h3 {{ font-size:15px; color:#2d3436; margin-bottom:8px; }}
.footer {{ text-align:center; padding:30px; color:#636e72; font-size:12px; }}
</style>
</head>
<body>
<div class="header">
<h1>AI Jobs Agent Dashboard</h1>
<p>Generated on {{ stats.get("date", "unknown") }} — Runtime: {runtime:.1f}s</p>
</div>
<div class="stats-grid">
<div class="stat-card"><div class="number">{total_scraped}</div><div class="label">Jobs Scraped</div></div>
<div class="stat-card"><div class="number">{total_recommended}</div><div class="label">Recommended</div></div>
<div class="stat-card"><div class="number">{total_applied}</div><div class="label">Applications</div></div>
<div class="stat-card"><div class="number">{runtime:.1f}s</div><div class="label">Runtime</div></div>
</div>
<div class="charts">
{charts_html}
</div>
<div class="footer">
Generated by AI Jobs Agent
</div>
{scripts_html}
</body>
</html>"""


def generate_dashboard(stats: Dict[str, Any]) -> str:
    """Generate HTML dashboard with Plotly charts.

    Args:
        stats: Dict containing pipeline statistics.

    Returns:
        Path to generated dashboard HTML file.
    """
    _ensure_dir()

    chart_divs = []
    chart_scripts = []
    chart_idx = 0

    source_stats = stats.get("source_stats", {})
    source_names = []
    source_jobs = []
    for name, s in source_stats.items():
        if isinstance(s, dict) and s.get("jobs_found", 0) > 0:
            source_names.append(name.capitalize())
            source_jobs.append(s.get("jobs_found", 0))

    if source_names:
        chart_divs.append(f'<div class="chart-container"><h3>Jobs by Source</h3><div id="chart_{chart_idx}"></div></div>')
        chart_scripts.append(f"""
Plotly.newPlot('chart_{chart_idx}', [{{
    x: {json.dumps(source_names)},
    y: {json.dumps(source_jobs)},
    type: 'bar',
    marker: {{ color: ['#0984e3', '#00b894', '#e17055'] }}
}}], {{
    margin: {{ t: 10, b: 30, l: 40, r: 10 }},
    height: 300,
    yaxis: {{ title: 'Jobs' }}
}}, {{ responsive: true }});""")
        chart_idx += 1

    daily_trend = stats.get("daily_trend", {})
    if daily_trend:
        dates = sorted(daily_trend.keys())
        counts = [daily_trend[d] for d in dates]
        chart_divs.append(f'<div class="chart-container"><h3>Daily Trend</h3><div id="chart_{chart_idx}"></div></div>')
        chart_scripts.append(f"""
Plotly.newPlot('chart_{chart_idx}', [{{
    x: {json.dumps(dates)},
    y: {json.dumps(counts)},
    type: 'scatter',
    mode: 'lines+markers',
    line: {{ color: '#0984e3', width: 2 }},
    marker: {{ size: 6 }}
}}, {{
    margin: {{ t: 10, b: 30, l: 40, r: 10 }},
    height: 300,
    yaxis: {{ title: 'Jobs' }}
}}, {{ responsive: true }});""")
        chart_idx += 1

    top_companies = stats.get("top_companies", [])
    if top_companies:
        companies = [c["name"] for c in top_companies[:10]]
        company_counts = [c["count"] for c in top_companies[:10]]
        chart_divs.append(f'<div class="chart-container"><h3>Top Companies</h3><div id="chart_{chart_idx}"></div></div>')
        chart_scripts.append(f"""
Plotly.newPlot('chart_{chart_idx}', [{{
    x: {json.dumps(company_counts)},
    y: {json.dumps(companies)},
    type: 'bar',
    orientation: 'h',
    marker: {{ color: '#00b894' }}
}}, {{
    margin: {{ t: 10, b: 30, l: 120, r: 10 }},
    height: 300,
    xaxis: {{ title: 'Jobs' }}
}}, {{ responsive: true }});""")
        chart_idx += 1

    top_categories = stats.get("top_categories", [])
    if top_categories:
        cats = [c["name"] for c in top_categories[:8]]
        cat_counts = [c["count"] for c in top_categories[:8]]
        chart_divs.append(f'<div class="chart-container"><h3>Top Categories</h3><div id="chart_{chart_idx}"></div></div>')
        chart_scripts.append(f"""
Plotly.newPlot('chart_{chart_idx}', [{{
    labels: {json.dumps(cats)},
    values: {json.dumps(cat_counts)},
    type: 'pie',
    hole: 0.4,
    marker: {{ colors: ['#0984e3','#00b894','#e17055','#fdcb6e','#6c5ce7','#e84393','#00cec9','#fab1a0'] }}
}}, {{
    margin: {{ t: 10, b: 10, l: 10, r: 10 }},
    height: 350,
    showlegend: true,
    legend: {{ orientation: 'h', y: -0.2 }}
}}, {{ responsive: true }});""")
        chart_idx += 1

    html = _build_html(stats, chart_divs, chart_scripts)
    html = html.replace("{{ stats.get(\"date\", \"unknown\") }}", stats.get("date", "unknown"))

    path = os.path.join(DASHBOARD_DIR, "index.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    log.info("Dashboard generated: %s", path)
    return path
